### ISSUE TITLE
Add caption to image

### ISSUE THREAD

**Issue by rjurado01** [NickKaramoff/vue-tinybox#24]
It would be great to add a caption to the image. Example:

![image](https://user-images.githubusercontent.com/1703608/79845424-4fda8500-83bd-11ea-8da8-c54044c7949f.png)

**Comment by NickKaramoff** [comment]
Yeah, I've been thinking about this as well. I'll try to get it done over this week

**Comment by NickKaramoff** [comment]
Released with [version 1.1.0](https://github.com/NickKaramoff/vue-tinybox/releases/tag/v1.1.0) 🎉
