### ISSUE TITLE
Close (maybe others) event(s)

### ISSUE THREAD

**Issue by JoaquimLey** [NickKaramoff/vue-tinybox#27]
**Is your feature request related to a problem?**
It would be great to have an event propagated when the component is closed

**Describe the solution you'd like**
Emit an event

**Additional context**
The reason behind this is my need to wrap the component into another component, where the index is passed down as prop. This prevents leaking the library to the whole codebase. But this issue I get with this is the mutation of the prop directly, I'm fine with this as long I was able to set that prop to null again (on the parent).

**Comment by NickKaramoff** [comment]
Published with [v1.3.0](https://github.com/NickKaramoff/vue-tinybox/releases/tag/v1.3.0) :tada:
